from pydantic import BaseModel
from typing import Optional


class BatteryFeatures(BaseModel):
    vehicle_brand: str
    vehicle_model: str
    vehicle_type: str
    manufacturing_year: float
    battery_manufacturer: str
    battery_chemistry: str
    battery_capacity_kwh: float
    drive_type: str
    odometer_km: float
    vehicle_age_years: float
    fleet_or_private: str
    cycle_count: float
    battery_health_percent: float
    state_of_charge: float
    depth_of_discharge: float
    state_of_health: float
    cell_voltage_avg: float
    cell_voltage_std: float
    pack_voltage: float
    cell_temperature_avg: float
    cell_temperature_max: float
    internal_resistance: float
    charge_efficiency: float
    discharge_efficiency: float
    remaining_capacity: float
    capacity_loss_percent: float
    charging_cycles_last_month: float
    fast_charge_ratio: float
    slow_charge_ratio: float
    average_charge_power_kw: float
    average_charging_time: float
    overnight_charging_ratio: float
    home_charging_ratio: float
    charging_interruptions: float
    overcharge_events: float
    average_speed: float
    average_trip_distance: float
    aggressive_acceleration_score: float
    hard_braking_score: float
    regenerative_braking_usage: float
    highway_driving_ratio: float
    city_driving_ratio: float
    daily_distance: float
    average_ambient_temperature: float
    maximum_temperature: float
    minimum_temperature: float
    humidity: float
    altitude: float
    terrain_type: str
    dust_exposure: float
    last_service_days: float
    cooling_system_health: float
    firmware_updates: float
    previous_faults: float
    maintenance_score: float
    thermal_runaway_risk: float
    voltage_imbalance: float
    temperature_variance: float
    sensor_fault_count: float
    BMS_warning_count: float
    abnormal_voltage_events: float
    battery_stress_index: float
    aging_score: float
    thermal_health_score: float
    charging_quality_score: float
    driving_stress_score: float
    predicted_remaining_life_cycles: float
